//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_scheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KanbanDatabaseEntities : DbContext
    {
        public KanbanDatabaseEntities()
            : base("name=KanbanDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERIOD> PERIODs { get; set; }
        public virtual DbSet<PERSON> People { get; set; }
        public virtual DbSet<USERSTORY> USERSTORies { get; set; }
    }
}
