//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_scheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSTORY
    {
        public int USERSTORY_SK { get; set; }
        public string TASK { get; set; }
        public int PERSON_FK { get; set; }
        public int PERIOD_FK { get; set; }
        public string STATUS { get; set; }
        public string PRIORITY { get; set; }
    
        public virtual PERIOD PERIOD { get; set; }
        public virtual PERSON PERSON { get; set; }
    }
}
